### ISSUE TITLE
Team Record Toggle

### ISSUE THREAD

**Issue by DravenSA** [vasqued2/ha-teamtracker-card#124]
Hi there, not an issue with the card more of a request.
Is there a way to hide the team_record value? with maybe a toggle option? 
I missed the first match of the preseason of the NBA, and when I looked at the card for the next match, I noticed my team was 1-0, this immediately let me know we had won the first match before I got a chance to watch it.

Thanks

**Comment by vasqued2** [comment]
You will want to hide the .record item using card-mod.

This wiki entry explains how. 

[https://github.com/vasqued2/ha-teamtracker/wiki/Using-CARD-MOD-card-to-format-the-TEAMTRACKER-CARD](https://github.com/vasqued2/ha-teamtracker/wiki/Using-CARD-MOD-card-to-format-the-TEAMTRACKER-CARD)

**Comment by DravenSA** [comment]
This worked,  great, guess i will need to add more conditional cards so I can turn on and off that stat at will, but this is a fix for now, thanks

**Comment by vasqued2** [comment]
I think you should be able to use a jinja2 template to set the value instead of simply hardcoding the value to `none` if you wanted to avoid conditional cards.  The second last example on the Wiki page shows how to use a template.  Just have to add in a conditional, but it seems like you should be able to do it.
