### ISSUE TITLE
Incorrect team icon

### ISSUE THREAD

**Issue by coleburg** [vasqued2/ha-teamtracker-card#18]
This was actually pretty funny as I have no idea what the image that was used is of.

![image](https://user-images.githubusercontent.com/13885439/201534769-b649dfa0-fdf7-4132-a98d-305738d300a8.png)

**Comment by vasqued2** [comment]
Are you using Chrome w/ extensions?  I've had the logos behave weird for me from time to time (i.e not displaying or displaying a completely different team) but never a completely different picture.  I assumed it had to do w/ an extension trying to save load times instead of repulling the image.  I generally refresh or clear cache and it cleared up.  

I'll pay more attention if I see it again to see if I can figure out what is going on.  If you can use the browser's Developer Tools to see if there are any error messages in the console, that could help too.

**Comment by vasqued2** [comment]
Fixed a typo impacting the logo on the right side of the POST card and haven't seen the problem since. Reopen if you continue to have it after upgrading for v0.5.4 or you see the problem on the left side or on other cards.
