### ISSUE TITLE
Date on card displaying as {common.today}

### ISSUE THREAD

**Issue by aetchells55** [vasqued2/ha-teamtracker-card#34]
In version 0.6.0, the date where it normally says Today or Tomorrow now displays at {common.today} or {common.tomorrow}.

I reverted.to 0.5.4 and the dates displayed as Today / Tomorrow as expected. 

Home Assistant System is set to Country: United States, Language: English. Time Zone: GMT -5:00 Eastern Time).

**Comment by vasqued2** [comment]
It's probably a cache issue.  Try clearing your cache and then refreshing  your browser or restarting the app.  It seems as though the language files aren't automatically refreshed when the card is upgraded in some configurations.

If it turns out to be a cache issue, let me know what app or browser you are using and it might help me see a trend.

**Comment by vasqued2** [comment]
Thanks.  It seems like Android may be the common thread.  Give me a place to start looking.
