### ISSUE TITLE
Don't show "away" team when displaying Golf tracker

### ISSUE THREAD

**Issue by brhahlen** [vasqued2/ha-teamtracker-card#52]
Created some sensors to track Golf and Golf players.
When using the card, it shows like this:
![image](https://user-images.githubusercontent.com/1798663/230035987-76ea958a-0f30-4ed6-861d-eaffa9da0fa9.png)

Ideally, for the Tournament, you'd want to show the leader only.
And for the individual tracker, just the golfer himself, without the "opponent".
Does that make sense?

All in all, thanks for the great card and integration!

**Comment by vasqued2** [comment]
It is working as I intended.

If you put in a golfers' name, it will show that golfer and the leader.  If you use the * as the wild card, it will show the golfers in first and second place.  These will be dynamically updated as they change throughout the competition.

Prior to the start of the tournament, it uses whatever tiebreaker rules ESPN uses since everyone is at par.

**Comment by brhahlen** [comment]
Ah, awesome!
I had not figured thatout, due to the fact that I don't know who Matthew McClean is :-)

Thanks for the clarification, looking forward to seeing what it looks like when the tournament actually starts!

**Comment by vasqued2** [comment]
Seems to be working for me.  Any issues?

**Comment by brhahlen** [comment]
Yes, works perfectly for me.
Thanks for the clarification and help!
