### ISSUE TITLE
Can't install from HACS or Link

### ISSUE THREAD

**Issue by jeroenvanadrichem** [vasqued2/ha-teamtracker-card#76]
Its not possible to download the card in HACS. I could not find the card and the download link in the readme file doens't work: 

Repository vasqued2/ha-teamtracker-card niet gevonden (did not found the card)

**Comment by vasqued2** [comment]
Have you used HACS to install other sensors and cards?  The button seems to be working for me and both are still listed in the HACS repository list so you should be able to search for them and find them without the button.

Are you using the "Explore and Download Repositories" button in the bottom left of HACS to search for it?

If you are, what happens when you click it and what are you doing next?

Also, what happens when you click on the install button in the README?  This really shouldn't be needed any more but it should still work.

**Comment by vasqued2** [comment]
Please reopen if you are still having this issue.

**Comment by bpwats** [comment]
@jeroenvanadrichem Setting HACS filtering from NL to all (restart HA) solved my issue of the card existing but not being able to find
